"""
Merge eval/cases/*.json into eval/gold_set.json (ADK evalset format).

Strips CoThesis metadata (source, expected_classification) before writing the
monolith. Cases are sorted deterministically by eval_id.

  python -m scripts.aggregate_gold_set
  python -m scripts.aggregate_gold_set --cases-dir eval/cases --out eval/gold_set.json
  python -m scripts.aggregate_gold_set --from-firestore
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CASES_DIR = ROOT / "eval" / "cases"
OUT_PATH = ROOT / "eval" / "gold_set.json"

METADATA_KEYS = frozenset({"source", "expected_classification"})

ENVELOPE = {
    "eval_set_id": "cothesis_pipeline_gold",
    "name": "CoThesis Pipeline Gold Set v2",
    "description": (
        "Hand-curated + HITL cases. rubric_based_final_response_quality_v1 + "
        "response_match_score. Generated by scripts/aggregate_gold_set.py."
    ),
}


def load_case(path: Path) -> dict:
    doc = json.loads(path.read_text(encoding="utf-8"))
    if "eval_id" not in doc:
        raise ValueError(f"{path}: missing eval_id")
    if "source" not in doc:
        raise ValueError(f"{path}: missing source metadata")
    if doc["source"].get("origin") not in {"seed", "hitl", "synthetic"}:
        raise ValueError(f"{path}: invalid source.origin")
    return doc


def to_adk_eval_case(case_doc: dict) -> dict:
    """Return ADK-native eval case (no CoThesis metadata)."""
    return {k: v for k, v in case_doc.items() if k not in METADATA_KEYS}


def aggregate_cases(case_paths: list[Path]) -> dict:
    cases = [load_case(p) for p in case_paths]
    cases.sort(key=lambda c: c["eval_id"])
    adk_cases = [to_adk_eval_case(c) for c in cases]
    return {
        **ENVELOPE,
        "eval_cases": adk_cases,
        "creation_timestamp": 0.0,
    }


def write_gold_set(out_path: Path, case_dir: Path = CASES_DIR) -> dict:
    paths = sorted(case_dir.glob("*.json"))
    if not paths:
        raise FileNotFoundError(f"No case files in {case_dir}")
    doc = aggregate_cases(paths)
    out_path.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    return doc


def main() -> int:
    parser = argparse.ArgumentParser(description="Aggregate eval/cases into eval/gold_set.json")
    parser.add_argument("--cases-dir", type=Path, default=CASES_DIR)
    parser.add_argument("--out", type=Path, default=OUT_PATH)
    parser.add_argument(
        "--from-firestore",
        action="store_true",
        help="Export eval_gold_cases from Firestore to --cases-dir first",
    )
    args = parser.parse_args()

    if args.from_firestore:
        from scripts.export_gold_from_firestore import export_cases

        export_cases(args.cases_dir)

    doc = write_gold_set(args.out, args.cases_dir)
    n = len(doc["eval_cases"])
    print(f"Wrote {n} cases -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
